/** Declaration file generated by dts-gen */

export class ScreepsServer {
    constructor(...args: any[]);

    connect(...args: any[]): void;

    setOpts(...args: any[]): void;

    start(...args: any[]): void;

    startProcess(...args: any[]): void;

    stop(...args: any[]): void;

    tick(...args: any[]): void;

    static defaultMaxListeners: number;

    static init(): void;

    static listenerCount(emitter: any, type: any): any;

    static once(emitter: any, name: any): any;

    static usingDomains: boolean;

}

export class TerrainMatrix {
    constructor(...args: any[]);

    get(...args: any[]): void;

    serialize(...args: any[]): void;

    set(...args: any[]): void;

    static unserialize(...args: any[]): void;

}

export namespace ScreepsServer {
    class EventEmitter {
        constructor();

        addListener(type: any, listener: any): any;

        emit(type: any, args: any): any;

        eventNames(): any;

        getMaxListeners(): any;

        listenerCount(type: any): any;

        listeners(type: any): any;

        off(type: any, listener: any): any;

        on(type: any, listener: any): any;

        once(type: any, listener: any): any;

        prependListener(type: any, listener: any): any;

        prependOnceListener(type: any, listener: any): any;

        rawListeners(type: any): any;

        removeAllListeners(type: any, ...args: any[]): any;

        removeListener(type: any, listener: any): any;

        setMaxListeners(n: any): any;

        static EventEmitter: any;

        static defaultMaxListeners: number;

        static init(): void;

        static listenerCount(emitter: any, type: any): any;

        static once(emitter: any, name: any): any;

        static usingDomains: boolean;

    }

}

export namespace stdHooks {
    function hookWrite(...args: any[]): void;

    function resetWrite(...args: any[]): void;

}

